#!/usr/bin/env bash

maxBrightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)
curBrightness=$(cat /sys/class/backlight/intel_backlight/brightness)
[[ "${curBrightness}" -le 0 ]] && exit
percent=$(echo "scale=0;${curBrightness} * 100 / ${maxBrightness}" | bc -l)
[[ "${percent}" -le 0 ]] && exit
echo "${percent}%"
