-- Language servers
require("servers.css")
require("servers.html")
require("servers.astro")
require("servers.gopls")
require("servers.bashls")
require("servers.eslint")
require("servers.jsonls")
require("servers.lua_ls")
require("servers.yamlls")
require("servers.pyright")
require("servers.emmet_ls")
require("servers.marksman")
require("servers.tsserver")
require("servers.tailwindcss")
require("servers.rust_analyzer")
require("servers.clangd")
